# Setting the theme

theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0

# Setting a title

title: Jurgden Portfolio
description: I want to showcase who I am, what I do and what I have to offer. 


# Optionals

show_downloads: "false"
google_analytics: G-Y523RKYQJ7
