# Setting the theme
theme: jekyll-theme-minimal

# Setting a title

title: Jurgden Portfolio
description: I want to showcase who I am, what I do and what I have to offer.

# Optionals

show_downloads: "false"
google_analytics: G-Y523RKYQJ7
